import {
  Brain,
  BarChart3,
  Users,
  Shield,
  Plug,
  Zap,
  LayoutDashboard,
  Lightbulb,
  GitBranch,
  Settings,
  ChevronRight,
  ChevronLeft,
  Menu,
  X,
  Moon,
  Sun,
  LogOut,
  User,
  Bell,
  Search,
  ChevronDown,
  Home,
  ArrowRight,
  Check,
  CheckCircle,
  HelpCircle,
  Loader2,
  AlertCircle,
  Plus,
  MoreHorizontal,
  Trash2,
  Edit,
  FolderKanban,
  MessageSquare,
  FileText,
  ExternalLink,
  Clock,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  brain: Brain,
  barChart: BarChart3,
  users: Users,
  shield: Shield,
  plug: Plug,
  zap: Zap,
  dashboard: LayoutDashboard,
  lightbulb: Lightbulb,
  gitBranch: GitBranch,
  settings: Settings,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  x: X,
  moon: Moon,
  sun: Sun,
  logOut: LogOut,
  user: User,
  bell: Bell,
  search: Search,
  chevronDown: ChevronDown,
  home: Home,
  arrowRight: ArrowRight,
  check: Check,
  checkCircle: CheckCircle,
  helpCircle: HelpCircle,
  spinner: Loader2,
  alertCircle: AlertCircle,
  plus: Plus,
  moreHorizontal: MoreHorizontal,
  trash: Trash2,
  edit: Edit,
  folderKanban: FolderKanban,
  messageSquare: MessageSquare,
  fileText: FileText,
  externalLink: ExternalLink,
  clock: Clock,
}